apiVersion: v1
kind: ConfigMap
metadata:
  name: shoppingapi-configmap 
data: 
  shoppingapi_url: http://shoppingapi-service
  #http://shoppingapi-service:8000
  #the above is coming from the shoppingapi-manfiest file. We kept the name as shoppingapi-service