apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: shoppingapi-hpa
spec:
  maxReplicas: 3 #define max replica count
  minReplicas: 2 # define min replica count
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shoppingapi-deployment
  targetCPUUtilizationPercentage: 50 #target cpu utilization
--- 
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: shoppingclientt-hpa
spec:
  maxReplicas: 3 #define max replica count
  minReplicas: 2 # define min replica count
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shoppingclient-deployment
  targetCPUUtilizationPercentage: 50 #target cpu utilization
    